# Generated by Django 4.1.3 on 2022-12-19 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('literaturecalendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='literaturecalendar.event')),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('AP', 'Approved'), ('RE', 'Rejected')], default='PE', max_length=2)),
            ],
            bases=('literaturecalendar.event',),
        ),
        migrations.AlterField(
            model_name='pendingarticle',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('AP', 'Approved'), ('RE', 'Rejected')], default='PE', max_length=2),
        ),
    ]
