# Generated by Django 4.1.3 on 2022-11-10 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='avatars', verbose_name='image')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='added at')),
            ],
            options={
                'verbose_name': 'avatar',
                'verbose_name_plural': 'avatars',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='profiles.avatar')),
            ],
        ),
    ]
